version: '3.6'
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "5000:80"
  app:
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api